// Generated by ReScript, PLEASE EDIT WITH CARE


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var Head = {};

var $$Error = {};

var Dynamic = {};

var Script = {};

var Html = {};

var DocumentHead = {};

var DocumentMain = {};

var DocumentNextScript = {};

export {
  GetServerSideProps ,
  GetStaticProps ,
  GetStaticPaths ,
  Link ,
  Router ,
  Head ,
  $$Error ,
  Dynamic ,
  Script ,
  Html ,
  DocumentHead ,
  DocumentMain ,
  DocumentNextScript ,
  
}
/* No side effect */
