// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Script from "next/script";

var id = "G-NVVEG6TXJK";

var Gtag = {
  id: id
};

function Analytics(Props) {
  var match = process.env.NODE_ENV;
  switch (match) {
    case "development" :
        return null;
    case "production" :
        return React.createElement(React.Fragment, undefined, React.createElement(Script, {
                        src: "https://www.googletagmanager.com/gtag/js?id=" + id,
                        strategy: "afterInteractive"
                      }), React.createElement(Script, {
                        id: "gtag-init",
                        strategy: "afterInteractive",
                        dangerouslySetInnerHTML: {
                          __html: "\n              window.dataLayer = window.dataLayer || [];\n              function gtag(){dataLayer.push(arguments);}\n              gtag('js', new Date());\n              gtag('config', '" + id + "}');\n            "
                        }
                      }));
    default:
      return null;
  }
}

var make = Analytics;

export {
  Gtag ,
  make ,
  
}
/* react Not a pure module */
