// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var PageComponent = {};

function $$default(props) {
  var content = React.createElement(props.Component, props.pageProps);
  return React.createElement("div", undefined, content);
}

export {
  PageComponent ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
