// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AuthorModuleCss from "./Author.module.css";

var styles = AuthorModuleCss;

function Author(Props) {
  var author = Props.author;
  if (author !== undefined) {
    return React.createElement("p", {
                style: styles.Author
              }, author);
  } else {
    return null;
  }
}

var make = Author;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
