// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as $$Document from "next/document";

function $$default(param) {
  return React.createElement($$Document.Html, {
              lang: "ko",
              children: null
            }, React.createElement($$Document.Head, {
                  children: null
                }, React.createElement("meta", {
                      content: "#f5cac3",
                      name: "theme-color"
                    }), React.createElement("meta", {
                      charSet: "utf-8"
                    }), React.createElement("link", {
                      href: "/favicon.ico",
                      rel: "icon",
                      sizes: "any"
                    }), React.createElement("link", {
                      href: "/favicon.svg",
                      rel: "icon",
                      type: "image/svg+xml"
                    }), React.createElement("link", {
                      href: "/logo192.png",
                      rel: "apple-touch-icon"
                    }), React.createElement("link", {
                      href: "/manifest.json",
                      rel: "manifest"
                    })), React.createElement("body", undefined, React.createElement($$Document.Main, {}), React.createElement($$Document.NextScript, {})));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
