// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Transition from "react-transition-group/Transition";

function Fade(Props) {
  var $$in = Props.in;
  var timeoutOpt = Props.timeout;
  var children = Props.children;
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 3000;
  return React.createElement(Transition, {
              in: $$in,
              timeout: timeout,
              children: (function (state) {
                  var opacity = state === "exited" || state === "exiting" ? 0 : 1;
                  var style = {
                    opacity: String(opacity),
                    transition: "opacity " + String(timeout) + "ms ease-in-out"
                  };
                  return React.createElement("div", {
                              style: style
                            }, children);
                })
            });
}

var make = Fade;

export {
  make ,
  
}
/* react Not a pure module */
