// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NavLink from "./NavLink.mjs";
import * as IconList from "./icons/IconList.mjs";
import * as IconSearch from "./icons/IconSearch.mjs";
import * as Router from "next/router";
import * as HeaderModuleCss from "./Header.module.css";

var styles = HeaderModuleCss;

function Header(Props) {
  var router = Router.useRouter();
  return React.createElement("header", {
              className: styles.Header
            }, React.createElement(NavLink.make, {
                  href: "/",
                  isActive: router.asPath === "/",
                  children: React.createElement("svg", {
                        height: "25",
                        width: "25",
                        fill: "none",
                        viewBox: "0 0 262 226",
                        xmlns: "http://www.w3.org/2000/svg"
                      }, React.createElement("path", {
                            d: "M100.602 0C44.1492 36.1022 0 94.5878 0 158.128C0 177.623 3.61878 196.396 11.5801 213.003C22.4365 222.39 34.0166 226 47.768 226C71.6519 226 86.8508 212.281 86.8508 185.566C86.8508 168.236 81.0608 153.073 58.6243 133.578L36.1878 114.805C51.3867 70.7604 71.6519 48.377 112.182 16.607L100.602 0ZM186.006 114.805C200.481 70.7604 221.47 48.377 262 16.607L249.696 0C193.243 36.1022 149.094 94.5878 149.094 158.128C149.094 177.623 153.436 196.396 160.674 213.003C172.254 222.39 183.834 226 196.862 226C220.746 226 236.669 212.281 236.669 185.566C236.669 168.236 230.155 153.073 208.442 133.578L186.006 114.805Z",
                            fill: "#517DB9"
                          }))
                }), React.createElement("div", {
                  className: styles["Header-right"]
                }, React.createElement(NavLink.make, {
                      href: "/list",
                      title: "\xea\xb8\xb0\xeb\xa1\x9d",
                      children: React.createElement(IconList.make, {})
                    }), React.createElement(NavLink.make, {
                      href: "/search",
                      title: "\xea\xb2\x80\xec\x83\x89",
                      isActive: router.asPath === "/search",
                      children: React.createElement(IconSearch.make, {})
                    })));
}

var make = Header;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
