// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fade from "./Fade.mjs";
import * as React from "react";

function Index(Props) {
  var total = Props.total;
  var children = Props.children;
  var lastIndex = total - 1 | 0;
  var match = React.useReducer((function (page, action) {
          if (action) {
            return Math.min(page + 1 | 0, lastIndex);
          } else {
            return Math.max(page - 1 | 0, 0);
          }
        }), 0);
  return React.createElement(Fade.make, {
              in: true,
              children: null
            }, React.createElement("div", undefined, String(match[0])), children);
}

var make = Index;

export {
  make ,
  
}
/* Fade Not a pure module */
