// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "./Header.mjs";
import * as LayoutModuleCss from "./Layout.module.css";

var styles = LayoutModuleCss;

function Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: styles.Layout
            }, React.createElement(Header.make, {}), React.createElement("div", {
                  className: "Layout-inner"
                }, children));
}

var make = Layout;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
