// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as NavLinkModuleCss from "./NavLink.module.css";

var styles = NavLinkModuleCss;

function NavLink(Props) {
  var href = Props.href;
  var titleOpt = Props.title;
  var isActive = Props.isActive;
  var children = Props.children;
  var title = titleOpt !== undefined ? titleOpt : "";
  var activeClassName = isActive !== undefined ? "is-active" : "";
  return React.createElement(Link, {
              href: href,
              children: React.createElement("a", {
                    className: styles.NavLink + " " + activeClassName,
                    title: title
                  }, children)
            });
}

var make = NavLink;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
