// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function QuoteList(Props) {
  var data = Props.data;
  return React.createElement("div", {
              className: "List"
            }, Belt_Array.map(data, (function (item) {
                    return React.createElement("div", {
                                key: item.id,
                                className: "List-item Item"
                              }, React.createElement("div", {
                                    className: "Item-quote",
                                    dangerouslySetInnerHTML: {
                                      __html: item.quote
                                    }
                                  }), React.createElement("div", {
                                    className: "Item-author",
                                    dangerouslySetInnerHTML: {
                                      __html: item.author
                                    }
                                  }));
                  })));
}

var make = QuoteList;

export {
  make ,
  
}
/* react Not a pure module */
