// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dayjs from "dayjs";
import * as React from "react";
import * as ReleasedModuleCss from "./Released.module.css";

var styles = ReleasedModuleCss;

var dateFormat = "YYYY\xeb\x85\x84 MM\xec\x9b\x94 DD\xec\x9d\xbc";

function getFormattedDate(date, format) {
  return Dayjs(date).format(format);
}

function Released(Props) {
  var created = Props.created;
  var released = Props.released;
  var title = created !== undefined ? Dayjs(created).format(dateFormat) : "";
  var releasedDate = released !== undefined ? Dayjs(released).format(dateFormat) : Dayjs(new Date()).format(dateFormat);
  return React.createElement("p", {
              className: styles.Released,
              title: title
            }, releasedDate);
}

var make = Released;

export {
  styles ,
  dateFormat ,
  getFormattedDate ,
  make ,
  
}
/* styles Not a pure module */
