// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as TagListModuleCss from "./TagList.module.css";

var styles = TagListModuleCss;

function TagList(Props) {
  var items = Props.items;
  return React.createElement("div", {
              className: "TagList"
            }, React.createElement("details", undefined, React.createElement("summary", {
                      className: styles["TagList-title"]
                    }, "\xea\xb2\x80\xec\x83\x89 \xea\xb8\xb0\xeb\xa1\x9d"), React.createElement("div", {
                      className: styles["TagList-items"]
                    }, Belt_Array.mapWithIndex(items, (function (index, item) {
                            return React.createElement("span", {
                                        key: String(index),
                                        className: styles["TagList-item"]
                                      }, item);
                          })))));
}

var make = TagList;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
