// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function IconList(Props) {
  return React.createElement("svg", {
              height: "24",
              width: "24",
              fill: "#442c2e",
              viewBox: "0 0 24 24",
              xmlns: "http://www.w3.org/2000/svg"
            }, React.createElement("g", {
                  fill: "none"
                }, React.createElement("path", {
                      d: "M0 0h24v24H0V0z"
                    }), React.createElement("path", {
                      d: "M0 0h24v24H0V0z",
                      opacity: ".87"
                    })), React.createElement("path", {
                  d: "M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7zm-4 6h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z"
                }));
}

var make = IconList;

export {
  make ,
  
}
/* react Not a pure module */
